### Add a new book

POST http://localhost:3000/api/books
Content-Type: application/json

{
  "title": "Brave New World",
  "author": "Aldous Huxley",
  "year": 1932,
  "genre":"Science fiction",
  "rating":4.3
}


### GET All Books
GET http://localhost:3000/api/books HTTP/1.1


### GET Book By ID
GET http://localhost:3000/api/books/is5avcd HTTP/1.1


### DELETE Book by ID

DELETE http://localhost:3000/api/books/is5avcd HTTP/1.1